---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
    type: front-end
  name: myapp-pod
  namespace: onoy-development
spec:
  containers:
    -
      image: nginx
      name: nginx-container
