---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
  namespace: onoy-development

spec:
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
      name: myapp-pod
    spec:
      containers:
        -
          image: nginx
          name: nginx-container
  replicas: 3

  selector:
    matchLabels:
      app: myapp
      type: front-end